### PR TITLE
Fixes navbar and login/Logout btn.

### LINKED ISSUE #38: [BUG]: Sticky Navbar not working properly in careers page
**Describe the bug**
When we are trying to scroll the careers page in Mobile or in responsive mode, the navbar is not sticked properly.

**To Reproduce**
1. Go to 'https://preciousitservices.vercel.app/index.html'
2. Click on ''Carrers section '
3. Scroll down to 

https://github.com/SyedImtiyaz-1/PreciousServices/assets/78204201/3c8e8f16-3881-4eff-805a-4b13cc282b21

**Expected behavior**
Navbar should stick properly with proper background colour.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ✓] I have checked the existing issues
- [✓ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ✓] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ ✓] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

### PR DESCRIPTION
**Pull request by Saifullah00**
fixes #38 
Navbar is working properly in Careers page.
Thankyou for Assigning.
Happy Hactoberfest'23

https://github.com/SyedImtiyaz-1/PreciousServices/assets/78204201/abcb7e46-27ff-4822-86ae-d203057a5874

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Great it will get merged on 1 Oct.

**Comment by SyedImtiyaz-1** [comment]
Your code have issues. @Saifullah00 Submit new PR.

**Comment by Saifullah00** [comment]
#38 is closed, can I work on it or you closed it?

**Comment by SyedImtiyaz-1** [comment]
raise new issue and submit the PR

**Pull request merged**
