### PR TITLE
Issue#53 resloved

### PR DESCRIPTION
**Pull request by Shivansh175**
I think it seems good now...please let me know if any more changes are required.

Screenshot 2023-09-30 162402

### CODE REVIEW

**Comment by Shivansh175** [comment]
hey @SyedImtiyaz-1 I made my PR but I think it has some issues....please help me out.

**Comment by SyedImtiyaz-1** [comment]
Don't decrease the size just use `z-index` to make it in upper portion

**Comment by Shivansh175** [comment]
okay

**Comment by Shivansh175** [comment]
Done Please have a look now

**Comment by SyedImtiyaz-1** [comment]
@Shivansh175 Great.
I will merge this on 1Oct

**Comment by Shivansh175** [comment]
why were these "check issues" arised when i made a pr? 
Will they cause any problem?

**Comment by Shivansh175** [comment]
> @Shivansh175 Great. I will merge this on 1Oct.

✨

**Comment by SyedImtiyaz-1** [comment]
> why were these "check issues" arised when i made a pr? Will they cause any problem?

No

**Comment by Shivansh175** [comment]
hey @SyedImtiyaz-1 please add the "hacktoberfest accepted" label as well

**Pull request merged**
