### PR TITLE
Fix typo in login button text

### LINKED ISSUE #63: [feat]: Login button
**Describe the bug**
The button says "Login" instead it should display "Log In"
**To Reproduce**
1. Go to "https://preciousitservices.vercel.app/"
2. On the top- right of Navigation bar. 
3. See the button which says "Login"

**Expected behavior**
The button says "Login" instead it should display "Log In"

**Screenshots**

image

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x ] I have checked the existing issues
- [ x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

### PR DESCRIPTION
**Pull request by Parvezkhan0**
Fixes #63

### CODE REVIEW

**Comment by Parvezkhan0** [comment]
@SyedImtiyaz-1 Why my checks failed. Did I made some mistakes here?

**Comment by SyedImtiyaz-1** [comment]
Bro don't change javascript this will break my codebase. Typo bug can only fixed in HTML.

**Comment by Parvezkhan0** [comment]
@SyedImtiyaz-1 Sorry for the confusion, can you give me another chance

**Comment by SyedImtiyaz-1** [comment]
Sure you can do again.

**Pull request closed without merging**
