### PR TITLE
Cards done

### PR DESCRIPTION
**Pull request by lalitjangir2002**
card_ui done with having some spacing between them.

Before changes:
Precious IT Services - Google Chrome 10_1_2023 6_53_07 PM

After Changes:
Precious IT Services - Google Chrome 10_1_2023 7_43_53 PM

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Resolve Conflicts

**Comment by lalitjangir2002** [comment]
yess

**Comment by lalitjangir2002** [comment]
Is there any error coming from my side?

**Comment by SyedImtiyaz-1** [comment]
No Issues.

**Pull request merged**
